modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"

[[mods]]
modId = "servux"
version = "${version}"
displayName = "ServuxForged"
displayURL="https://github.com/ThinkingStudios/Servux-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Servux unofficial (Neo)Forge port.

Server-side support and integration for masa's client mods.
'''
displayTest = "IGNORE_SERVER_VERSION"

[[mixins]]
config = "mixins.servux.json"

[[dependencies.servux]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.servux]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "SERVER"
