modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"

[[mods]]
modId = "servux"
version = "${version}"
displayName = "ServuxForged"
displayURL="https://github.com/ThinkingStudios/Servux-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Servux unofficial (Neo)Forge port.

Server-side support and integration for masa's client mods.
'''

[[mixins]]
config = "servux.mixins.json"

[[dependencies.servux]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.servux]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.servux]]
modId = "badpackets"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "SERVER"
